In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import project_path
import numpy as np
import pandas as pd
import time
from dataset import MultiOutputDataset
from collections import Counter
from sklearn.tree import DecisionTreeClassifier

ImportError: cannot import name 'MultiOutputDataset'

In [76]:
X = pd.read_pickle('../XYdatasets/cruise-latest_X.pickle')
Y = np.load('../XYdatasets/cruise-latest_Y.npy')
X_orig = pd.read_pickle('../XYdatasets/cruise-latest_X.pickle')
Y_orig = np.load('../XYdatasets/cruise-latest_Y.npy')

In [77]:
m = np.max(np.nonzero(Y)[1]) + 1
l = []
for row in Y:
    values = list(np.nonzero(row)[0] + 1)
    filler = [0] * (m - len(values))
    l.append(values + filler)
np.array(l)

array([[1, 3, 0],
       [1, 2, 3],
       [1, 2, 3],
       ...,
       [1, 2, 3],
       [1, 3, 0],
       [1, 2, 3]])

In [79]:
Y[Y[:,3] != 0]

array([], shape=(0, 4), dtype=int64)

In [68]:
np.nonzero([1,0,1])[0] + 1

array([1, 3])

In [17]:
arr = np.array([[1,2,4,0,0],[5,8,1,2,0],[3,5,0,2,0],[2,0,0,0,0]])
arr2 = np.array([[7,3,2,0,0],[4,1,0,0,0],[6,0,0,0,0]])
arr3 = np.array([[7,3,2,0,0],[4,1,0,0,0],[6,0,0,0,0]])

In [9]:
b = np.bincount(arr.flatten())
b[0] = 0
b

array([0, 2, 1, 1, 1, 2, 0, 0, 1])

In [10]:
    def get_max_labels(labels):
        label_counts = np.bincount(labels.flatten())
        label_counts[0] = -1  # Ignore count of zeros since we use it only as a filler
        new_labels = []
        for i in range(len(labels)):
            current = labels[i]
            max_label = max(list(current), key=lambda l: label_counts[l])
            assert max_label != -1
            new_labels.append(max_label)
        return np.array(new_labels)

In [18]:
get_max_labels(arr)

array([2, 2, 2, 2])

In [7]:
np.count_nonzero(np.array([[1,1,0,1,0,0,0,0],[1,0,0,0,1,0,0,1],[1,0,1,0,0,0,0,0]]), axis=0)

array([3, 1, 1, 1, 1, 0, 0, 1])

In [30]:
np.dstack((arr, arr2, arr3))

array([[[1, 7, 7],
        [2, 3, 3],
        [4, 2, 2],
        [0, 0, 0],
        [0, 0, 0]],

       [[5, 4, 4],
        [8, 1, 1],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[3, 6, 6],
        [1, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [83]:
    def convert_vector_labels_to_new_format(labels):
        m = np.max(np.nonzero(labels)[1]) + 1
        l = []
        for row in labels:
            values = list(np.nonzero(row)[0] + 1)
            filler = [0] * (m - len(values))
            l.append(values + filler)
        return np.array(l)

In [84]:
Y = convert_vector_labels_to_new_format(Y)
{x:x for x in Y.flatten()}

{1: 1, 3: 3, 0: 0, 2: 2}