In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
from dataset.multi_output_dataset import MultiOutputDataset
from dataset.single_output_dataset import SingleOutputDataset
from sklearn.tree import DecisionTreeClassifier

In [51]:
x = np.array(pd.read_pickle('../XYdatasets/cruise-latest_old.vector'))
y = np.load('../XYdatasets/cruise-latest_old.npy')

In [52]:
    def convert_vector_labels_to_new_format(labels):
        m = np.max(np.nonzero(labels)[1]) + 1
        l = []
        for row in labels:
            values = list(np.nonzero(row)[0] + 1)
            filler = [-1] * (m - len(values))
            l.append(values + filler)
        return np.array(l)

In [53]:
y = convert_vector_labels_to_new_format(y)

In [54]:
    def _get_max_labels(labels):
        flattened_labels = labels.flatten()
        # remove -1 as we use it only as a filler
        flattened_labels = flattened_labels[flattened_labels != -1]
        label_counts = np.bincount(flattened_labels)
        new_labels = []
        for i in range(len(labels)):
            current = labels[i]
            current = current[current != -1]
            max_label = max(list(current), key=lambda l: label_counts[l])
            assert max_label != -1
            new_labels.append(max_label)
        return np.array(new_labels), label_counts

In [55]:
det_y, counts = _get_max_labels(y)

In [56]:
np.bincount(det_y)

array([     0,  14821,      0, 281149])

In [111]:
np.bincount(det_l)

array([     0,    175,    204,    264,    200,    251,    260,    333,
          287,    304,    145,    230,    304,    259,    246,    210,
          217,    259,    259,    204,    316,    212,    216,    276,
          288,    404,    329,    440,    324,    278,    334,    338,
          316,    375,    264,    374,    336,    365, 518022,    211,
          188,    231])

In [112]:
np.bincount(det_r)

array([     0,    489,    640,    604,    509,    595,    696,    600,
          498,    473,    556,    652,    557,    565,    502,    541,
          503,    540,    454,    418,    550,    385,    470,    481,
          437,    537,    452,    379,    364,    384,    457,    420,
          428,    243,    369,    292,    351,    332,    476, 837706,
          603,    655])